pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello'
            }
        }
        stage('Bolo') {
            steps {
                echo 'bolo'
            }
        }
    }
}
